"use client";
import { useEffect, useState } from "react";
import { UploadCloud, Brain, BarChart3, Activity, User, Home, GraduationCap, Radio, Crown } from "lucide-react";
import { supabase } from "../lib/supabase";
export default function HomePage(){
const [session,setSession]=useState<any>(null); const [loadingAuth,setLoadingAuth]=useState(true); const [tab,setTab]=useState("home"); const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState(""); const [result,setResult]=useState("نتيجة التحليل تظهر هنا."); const [loading,setLoading]=useState(false); const [question,setQuestion]=useState("");
useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoadingAuth(false)}); const {data:listener}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>listener.subscription.unsubscribe()},[]);
async function signInGoogle(){await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:"https://flow-academy-ai.vercel.app"}})}
async function signOut(){await supabase.auth.signOut();setSession(null)}
function onFile(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0]; if(!f)return; setFile(f); setPreview(URL.createObjectURL(f)); setResult("تم رفع الصورة. اضغط حلل الآن.")}
async function analyze(){if(!file)return setResult("ارفع صورة الشارت أولاً."); setLoading(true); setResult("جاري قراءة الشارت وتحليل ICT..."); const data=new FormData(); data.append("image",file); try{const res=await fetch("/api/analyze",{method:"POST",body:data}); const json=await res.json(); setResult(json.analysis||"لم تصل نتيجة تحليل.")}catch{setResult("تعذر الاتصال بالمحرك.")}finally{setLoading(false)}}
function ask(){if(!question.trim())return; setResult(`سؤال المستشار:\n${question}\n\nسيتم ربط هذه الصفحة لاحقاً ببيانات الحساب والشارت.\nالمنهج المعتمد: ICT فقط.`); setTab("home")}
if(loadingAuth)return <main className="login"><div className="login-card">جاري التحميل...</div></main>;
if(!session)return <main className="login"><section className="login-card"><div className="logo" style={{margin:"auto"}}>F</div><h1 style={{marginTop:16}}>Flow Academy AI</h1><p className="sub">منصة أكاديمية فلو للتحليل والتعليم والإشارات</p><div className="ai-box" style={{marginTop:18}}>سجّل دخولك بحساب Google حتى تستخدم التطبيق وتتابع اشتراكك وتحليلاتك.</div><button className="google" onClick={signInGoogle}>تسجيل الدخول بواسطة Google</button></section></main>;
return <main className="phone"><header className="top"><div className="brand"><div className="logo">F</div><div><h1>Flow Academy AI</h1><p className="sub">محلل ICT عربي</p></div></div><div className="pill">Free</div></header>
<section className={tab!=="home"?"hidden":""}><section className="hero"><small>مرحباً بك</small><h2>ماذا تريد اليوم؟</h2><div className="ai-box">تحليل سكالب وسوينغ، إشارات، مستشار، وأكاديمية تعليمية بمنهج ICT و CRT.</div></section><section className="grid"><div className="mini"><b>سكالب</b><span>15M + 5M + 1M</span></div><div className="mini"><b>سوينغ</b><span>D1 + H4 + H1</span></div></section><section className="card"><div className="card-title"><div className="icon"><UploadCloud size={23}/></div><h3>تحليل الشارت</h3></div><label className="upload"><input type="file" accept="image/*" onChange={onFile}/><div><UploadCloud size={34}/><p>اضغط هنا لرفع صورة الشارت</p></div></label>{preview&&<img className="preview" src={preview} style={{display:"block"}} alt="chart preview"/>}<button className="btn" onClick={analyze} disabled={loading}>{loading?"جاري التحليل...":"حلل الآن"}</button><div className={`result ${result==="نتيجة التحليل تظهر هنا."?"empty":""}`}>{result}</div></section></section>
<section className={`card ${tab!=="advisor"?"hidden":""}`}><div className="card-title"><div className="icon"><Brain size={23}/></div><h3>المستشار</h3></div><label className="upload"><input type="file" accept="image/*"/><p>ارفع صورة الشارت</p></label><label className="upload" style={{marginTop:12}}><input type="file" accept="image/*"/><p>ارفع صورة الحساب والهامش</p></label><textarea value={question} onChange={(e)=>setQuestion(e.target.value)} placeholder="مثال: هل أثبت الصفقة؟ هل أحرك الستوب؟ وين السيولة القادمة؟"/><button className="btn" onClick={ask}>اسأل المستشار</button></section>
<section className={`card ${tab!=="signals"?"hidden":""}`}><div className="card-title"><div className="icon"><Radio size={23}/></div><h3>الإشارات</h3></div><div className="result">Flow Academy VIP{"\n"}XAUUSD BUY 4148{"\n"}TP1 4152{"\n"}TP2 4156{"\n"}TP3 4160{"\n"}SL 4134{"\n\n"}الحالة: نشطة</div></section>
<section className={`card ${tab!=="performance"?"hidden":""}`}><div className="card-title"><div className="icon"><Activity size={23}/></div><h3>الأداء</h3></div><section className="grid"><div className="mini"><b>79%</b><span>دقة الأداء</span></div><div className="mini"><b>0</b><span>تحليلاتك</span></div></section></section>
<section className={`card ${tab!=="academy"?"hidden":""}`}><div className="card-title"><div className="icon"><GraduationCap size={23}/></div><h3>الأكاديمية</h3></div><div className="feature">الأخبار الاقتصادية</div><div className="feature">المقالات الاقتصادية</div><div className="feature">التحليل اليومي</div><div className="feature">دروس ICT و CRT</div><div className="feature">الويبينارات</div></section>
<section className={`card ${tab!=="profile"?"hidden":""}`}><div className="card-title"><div className="icon"><User size={23}/></div><h3>ملفي الشخصي</h3></div><p>{session.user?.email}</p><p style={{marginTop:10}}>الخطة الحالية: <span className="plan">Flow Free</span></p><button className="btn-dark" onClick={()=>setTab("plans")}>ترقية الحساب</button><button className="logout" onClick={signOut} style={{marginTop:20}}>تسجيل خروج</button></section>
<section className={`card ${tab!=="plans"?"hidden":""}`}><div className="card-title"><div className="icon"><Crown size={23}/></div><h3>اختر خطتك</h3></div><div className="result">Flow Free{"\n"}$0{"\n"}تحليل واحد يومياً + الأخبار + بعض الإشارات القديمة</div><div className="result">Flow Trader{"\n"}$19.99/mo{"\n"}10 تحليلات يومياً + مستشار 5 مرات + الإشارات + الأكاديمية</div><div className="result">Flow Elite{"\n"}$49.99/mo{"\n"}غير محدود + إشارات VIP + مستشار غير محدود + دعم أولوية</div></section>
<nav className="bottom"><button className={`navbtn ${tab==="home"?"active":""}`} onClick={()=>setTab("home")}><Home size={20}/>الرئيسية</button><button className={`navbtn ${tab==="advisor"?"active":""}`} onClick={()=>setTab("advisor")}><Brain size={20}/>المستشار</button><button className={`navbtn ${tab==="signals"?"active":""}`} onClick={()=>setTab("signals")}><Radio size={20}/>الإشارات</button><button className={`navbtn ${tab==="performance"?"active":""}`} onClick={()=>setTab("performance")}><BarChart3 size={20}/>الأداء</button><button className={`navbtn ${tab==="academy"?"active":""}`} onClick={()=>setTab("academy")}><GraduationCap size={20}/>الأكاديمية</button><button className={`navbtn ${tab==="profile"?"active":""}`} onClick={()=>setTab("profile")}><User size={20}/>ملفي</button></nav></main>}
